// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

/**
 * @title ZKMotusRegistry
 * @author Yabes Theodorus
 * @notice Registers and verifies authenticity of purchased items using ZK proofs.
 * @dev
 * - Serial numbers are hashed off-chain (e.g. Poseidon) before reaching this contract.
 * - Buyer identity is never stored or revealed on-chain.
 * - Ownership is represented solely via a purchase commitment.
 * - ZK proofs attest knowledge of (secret, serial) matching the stored commitment.
 * - Verification is merchant-gated and nonce-protected to prevent replay.
 */
import {ZKMotusPayment} from "./ZKMotusPayment.sol";
import {IVerifier} from "./ZKMotusVerifier.sol";

contract ZKMotusRegistry {
    /*////////////////////////////////////////////////////////////////////////////
                                          ERRORS
    ///////////////////////////////////////////////////////////////////////////*/

    /// @notice Thrown when attempting to register an already-registered serial
    error ZKMotusRegistry__ItemsAlreadyRegistered(bytes32 serialNumber);

    /// @notice Thrown when provided commitment does not match payment record
    error ZKMotusRegistry__UnauthorizedBuyer(bytes32 serialNumber);

    /// @notice Thrown when serial number has not been paid for
    error ZKMotusRegistry__ItemNotPaid(bytes32 serialNumber);

    /// @notice Thrown when a non-merchant calls a restricted function
    error ZKMotusRegistry__NotFromMerchant(address sender);

    /// @notice Thrown when zero address is supplied
    error ZKMotusRegistry__ZeroValue();

    /// @notice Thrown when verifying an unregistered serial
    error ZKMotusRegistry__ItemNotRegistered(bytes32 serialNumber);

    /// @notice Thrown when nonce has already been used
    error ZKMotusRegistry__InvalidNonce(bytes32 nonce);

    /// @notice Thrown when ZK proof verification fails
    error ZKMotusRegistry__InvalidProof();

    /*////////////////////////////////////////////////////////////////////////////
                                    STATE VARIABLES
    ///////////////////////////////////////////////////////////////////////////*/

    /// @notice Merchant address authorized to verify authenticity
    address private immutable i_merchant;

    /// @notice ZK verifier contract (generated by Noir / Plonk / Groth16 etc.)
    IVerifier private immutable i_zkVerifier;

    /// @notice Payment contract used as the source of truth for purchases
    ZKMotusPayment private immutable i_paymentContract;

    /// @notice Maps hashed serial number to its purchase commitment
    mapping(bytes32 serialNumber => bytes32 authenticityCommitment)
        private s_serialNumberToPurchaseCommitment;

    /// @notice Tracks used nonces to prevent replay of proofs
    mapping(bytes32 nonce => bool used) private s_nonceIsUsed;

    /*////////////////////////////////////////////////////////////////////////////
                                          EVENTS
    ///////////////////////////////////////////////////////////////////////////*/

    /// @notice Emitted when an item is registered for authenticity
    event ItemsAuthenticityRegistered(bytes32 indexed serialNumber);

    /// @notice Emitted when an item’s authenticity is successfully verified
    event AuthenticityVerified(bytes32 indexed serialNumber);

    /*////////////////////////////////////////////////////////////////////////////
                                         MODIFIERS
    ///////////////////////////////////////////////////////////////////////////*/

    /// @notice Restricts function access to the merchant
    modifier onlyMerchant() {
        if (msg.sender != i_merchant) {
            revert ZKMotusRegistry__NotFromMerchant(msg.sender);
        }
        _;
    }

    /*////////////////////////////////////////////////////////////////////////////
                                        CONSTRUCTOR
    ///////////////////////////////////////////////////////////////////////////*/

    /**
     * @param _paymentContract Address of the ZKMotusPayment contract
     * @param _merchantAddress Merchant authorized to verify proofs
     * @param zkVerifier Address of the deployed ZK verifier contract
     */
    constructor(
        address payable _paymentContract,
        address _merchantAddress,
        address zkVerifier
    ) {
        if (
            _merchantAddress == address(0) ||
            _paymentContract == address(0) ||
            zkVerifier == address(0)
        ) {
            revert ZKMotusRegistry__ZeroValue();
        }
        i_merchant = _merchantAddress;
        i_zkVerifier = IVerifier(zkVerifier);
        i_paymentContract = ZKMotusPayment(_paymentContract);
    }

    /*////////////////////////////////////////////////////////////////////////////
                                   RECEIVE / FALLBACK
    ///////////////////////////////////////////////////////////////////////////*/

    /*////////////////////////////////////////////////////////////////////////////
                               PUBLIC / EXTERNAL FUNCTIONS
    ///////////////////////////////////////////////////////////////////////////*/

    /**
     * @notice Registers an item’s authenticity after successful payment
     * @dev
     * - Caller supplies the purchase commitment and hashed serial number.
     * - Commitment must match the one recorded in the payment contract.
     * - This step binds the serial number to the commitment permanently.
     *
     * @param _authenticityCommitment Commitment for registering authenticity
     * @param _orderCommitment Commitment submitted when paying order
     * @param _serialNumber Hashed serial number of the item
     */
    function registerAuthenticity(
        bytes32 _authenticityCommitment,
        bytes32 _orderCommitment,
        bytes32 _serialNumber
    ) external {
        if (_authenticityCommitment == bytes32(0)) {
            revert ZKMotusRegistry__ZeroValue();
        }
        // user registering purchased item by providing purchase commitment, orderId, and serial number
        // firstly, check to payment contract if the items already paid, and paid by correct address
        bytes32 commitment = i_paymentContract.getCommitmentFromSerialNumber(
            _serialNumber
        );

        if (commitment == bytes32(0)) {
            revert ZKMotusRegistry__ItemNotPaid(_serialNumber);
        }

        // If different person try to registerAuthenticity upon an item she doesn't paid
        // contract will check whether valid commitment are sumitted
        if (commitment != _orderCommitment) {
            revert ZKMotusRegistry__UnauthorizedBuyer(_serialNumber);
        }

        // check whether purchase commitment already exist for that serial number
        if (s_serialNumberToPurchaseCommitment[_serialNumber] != bytes32(0)) {
            revert ZKMotusRegistry__ItemsAlreadyRegistered(_serialNumber);
        }

        // store purchase commitment mapped to serial number
        s_serialNumberToPurchaseCommitment[
            _serialNumber
        ] = _authenticityCommitment;

        emit ItemsAuthenticityRegistered(_serialNumber);
    }

    /**
     * @notice Verifies authenticity of an item using a zero-knowledge proof
     * @dev
     * - Callable only by merchant (e.g. in-store or backend verification).
     * - Proof must attest knowledge of secret + serial matching the commitment.
     * - Nonce is enforced as single-use to prevent replay.
     *
     * @param _proof Zero-knowledge proof bytes
     * @param _serialNumber Hashed serial number being verified
     * @param _nonce One-time nonce included in the proof public inputs
     *
     */
    function verifyAuthenticity(
        bytes calldata _proof,
        bytes32 _serialNumber,
        bytes32 _nonce
    ) external onlyMerchant {
        if (s_nonceIsUsed[_nonce]) {
            revert ZKMotusRegistry__InvalidNonce(_nonce);
        }
        bytes32[] memory publicInputs = new bytes32[](3);
        bytes32 authenticityCommitment = s_serialNumberToPurchaseCommitment[
            _serialNumber
        ];

        if (authenticityCommitment == bytes32(0)) {
            revert ZKMotusRegistry__ItemNotRegistered(_serialNumber);
        }

        publicInputs[0] = authenticityCommitment;
        publicInputs[1] = _serialNumber;
        publicInputs[2] = _nonce;

        try i_zkVerifier.verify(_proof, publicInputs) returns (bool ok) {
            if (!ok) revert ZKMotusRegistry__InvalidProof();
        } catch (bytes memory revertData) {
            revert ZKMotusRegistry__InvalidProof();
        }
        s_nonceIsUsed[_nonce] = true;
        emit AuthenticityVerified(_serialNumber);
    }

    /*////////////////////////////////////////////////////////////////////////////
                             INTERNAL / PRIVATE FUNCTIONS
    ///////////////////////////////////////////////////////////////////////////*/

    /*////////////////////////////////////////////////////////////////////////////
                                VIEW / PURE FUNCTIONS
    ///////////////////////////////////////////////////////////////////////////*/
}
